image:
  repository: coderiseio/udp-listener
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

serviceAccount:
  create: true

service:
  type: LoadBalancer
  port: 5005
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
    #service.beta.kubernetes.io/aws-load-balancer-eip-allocations: eipalloc-00335db241ka2fs1n
    #service.beta.kubernetes.io/aws-load-balancer-subnets: coderise_sample_subnet
    #service.beta.kubernetes.io/aws-load-balancer-security-groups: sg-0913f81f52beb4f4a
    service.beta.kubernetes.io/aws-load-balancer-type: nlb