name: udp-listener-5006
image:
  repository: coderiseio/udp-listener
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

serviceAccount:
  create: true

service:
  type: LoadBalancer
  port: 5006
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: eipalloc-057553b2156ec2c74
    service.beta.kubernetes.io/aws-load-balancer-subnets: coderise_test_vpc_ca-Public1
    service.beta.kubernetes.io/aws-load-balancer-security-groups: sg-0913f81f52beb4f4a
    service.beta.kubernetes.io/aws-load-balancer-type: nlb