apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  labels:
    {{- include "udp-listener.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: UDP
      name: udp
  selector:
    {{- include "udp-listener.selectorLabels" . | nindent 4 }}
